export const LOAD_EVENTS_SUCCESS ='LOAD_EVENTS_SUCCESS';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const INCREASE_AVAILABILITY_SUCCESS= 'INCREASE_AVAILABILITY_SUCCESS';
export const DECREASE_AVAILABILITY_SUCCESS= 'DECREASE_AVAILABILITY_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const REGISTER_TO_EVENT_SUCCESS = 'REGISTER_TO_EVENT_SUCCESS';
export const CANCEL_REGISTRATION_SUCCESS = 'CANCEL_REGISTRATION_SUCCESS';
export const SIGNIN_SUCCESS='SIGNIN_SUCCESS';
export const SIGNOUT_SUCCESS='SIGNOUT_SUCCESS';
export const AUTHENTICATED = 'AUTHENTICATED';
export const NOT_AUTHENTICATED='NOT_AUTHENTICATED';
